name: CI
on:
  push:
  pull_request:
jobs:
  golangci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: ^1
      - uses: actions/checkout@v4
      - name: get dependencies
        run: go mod download
      - name: lint
        uses: golangci/golangci-lint-action@v4
      - name: install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: run gofumpt
        run: gofumpt -l -w .
      - name: run test
        run: go test ./rpc/rpc_test.go
      - name: build
        run: go build ./main.go
